import React from "react";

const ProductForm = ({ product, handleChange }) => {
  return (
    <div className="addProductsForm">
      <form>
        <div>
          <label>Image URL:</label>
          <input
            type="text"
            name="Image"
            value={product.Image}
            onChange={handleChange}
          />
        </div>
        <div>
          <label>Name:</label>
          <input
            type="text"
            name="Name"
            value={product.Name}
            onChange={handleChange}
          />
        </div>
        <div>
          <label>Brand:</label>
          <input
            type="text"
            name="Brand"
            value={product.Brand}
            onChange={handleChange}
          />
        </div>
        <div>
          <label>Type:</label>
          <input
            type="text"
            name="Type"
            value={product.Type}
            onChange={handleChange}
          />
        </div>
        <div>
          <label>Category:</label>
          <input
            type="text"
            name="Category"
            value={product.Category}
            onChange={handleChange}
          />
        </div>
        <div>
          <label>Description:</label>
          <input
            type="text"
            name="Description"
            value={product.Description}
            onChange={handleChange}
          />
        </div>
        <div>
          <label>Size:</label>
          <input
            type="text"
            name="Size"
            value={product.Size}
            onChange={handleChange}
          />
        </div>
        <div>
          <label>Price:</label>
          <input
            type="text"
            name="Price"
            value={product.Price}
            onChange={handleChange}
          />
        </div>
        <div>
          <label>Stock:</label>
          <input
            type="text"
            name="Stock"
            value={product.Stock}
            onChange={handleChange}
          />
        </div>
      </form>
    </div>
  );
};

export default ProductForm;
